//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication29mvc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AugustDBEntities : DbContext
    {
        public AugustDBEntities()
            : base("name=AugustDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<dept2> dept2 { get; set; }
        public virtual DbSet<order3> order3 { get; set; }
        public virtual DbSet<orderN> orderNs { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<tab1N> tab1N { get; set; }
        public virtual DbSet<table1> table1 { get; set; }
        public virtual DbSet<table2> table2 { get; set; }
        public virtual DbSet<emp2> emp2 { get; set; }
        public virtual DbSet<emp3> emp3 { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<salesbyregion> salesbyregions { get; set; }
        public virtual DbSet<signuppage> signuppages { get; set; }
        public virtual DbSet<sigup> sigups { get; set; }
        public virtual DbSet<stud> studs { get; set; }
    
        public virtual int addemp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addemp");
        }
    
        public virtual int addsig()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addsig");
        }
    
        public virtual int delemp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delemp");
        }
    
        public virtual int delsig()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delsig");
        }
    
        public virtual int empadd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("empadd");
        }
    
        public virtual ObjectResult<SelectAllEmp_Result> SelectAllEmp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllEmp_Result>("SelectAllEmp");
        }
    
        public virtual ObjectResult<selemp_Result> selemp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selemp_Result>("selemp");
        }
    
        public virtual ObjectResult<selsig_Result> selsig()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<selsig_Result>("selsig");
        }
    
        public virtual int sp_stinsert(string sna, Nullable<int> sag, string sadd)
        {
            var snaParameter = sna != null ?
                new ObjectParameter("sna", sna) :
                new ObjectParameter("sna", typeof(string));
    
            var sagParameter = sag.HasValue ?
                new ObjectParameter("sag", sag) :
                new ObjectParameter("sag", typeof(int));
    
            var saddParameter = sadd != null ?
                new ObjectParameter("sadd", sadd) :
                new ObjectParameter("sadd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_stinsert", snaParameter, sagParameter, saddParameter);
        }
    
        public virtual int studadd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("studadd");
        }
    
        public virtual int studdel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("studdel");
        }
    
        public virtual ObjectResult<studsel_Result> studsel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<studsel_Result>("studsel");
        }
    
        public virtual int studupdate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("studupdate");
        }
    
        public virtual int updateemp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateemp");
        }
    
        public virtual int upsig()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upsig");
        }
    }
}
