//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication29mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesbyregion
    {
        public int year { get; set; }
        public string east { get; set; }
        public string west { get; set; }
    }
}
